version: "3.9"

services:
  dockermanager:
    image: ghcr.io/powernet-git/tcx-dockermanager:v1.0.13
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 1s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        # Traefik labels for external access
        - "traefik.enable=true"
        - "traefik.http.routers.dockermanager.rule=Host(`dockermanager.telecomx.dk`)"
        - "traefik.http.routers.dockermanager.entrypoints=websecure"
        - "traefik.http.routers.dockermanager.tls.certresolver=le-dns"
        # Restrict access to 62.192.160.0/24
        - "traefik.http.routers.dockermanager.middlewares=dockermanager-ipallowlist"
        - "traefik.http.middlewares.dockermanager-ipallowlist.ipallowlist.sourcerange=62.192.160.0/24"
        # Service listens on port 80
        - "traefik.http.services.dockermanager.loadbalancer.server.port=80"
        # Optional: Enable sticky sessions if you want consistent node targeting
        # - "traefik.http.services.dockermanager.loadbalancer.sticky.cookie=true"
        # - "traefik.http.services.dockermanager.loadbalancer.sticky.cookie.name=docker_proxy_node"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - traefik_public
      - internal
    environment:
      - PORT=80
      - NODE_HOSTNAME={{.Node.Hostname}}
      - SERVICE_NAME=dockermanager_dockermanager
      - LOG_LEVEL=info
    secrets:
      - dockermanager_api_auth_token
      - ghcr_username
      - ghcr_token

networks:
  traefik_public:
    external: true
    name: traefik_traefik_public
  internal:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: "1450"

secrets:
  dockermanager_api_auth_token:
    external: true
  ghcr_username:
    external: true
  ghcr_token:
    external: true